name: Build ezDV

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install prerequisite packages
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install git wget flex bison gperf python3 python3-pip python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0

      - name: Install ESP-IDF
        shell: bash
        run: |
          git clone -b v5.3 --recursive https://github.com/espressif/esp-idf.git
          cd esp-idf
          ./install.sh all

      - name: Build project
        shell: bash
        run: |
          . ./esp-idf/export.sh
          cd firmware
          idf.py build

      - name: Create release assets
        shell: bash
        run: |
          cd firmware/build
          mkdir release
          cd release
          cp ../ezdv.bin .
          cp ../http_0.bin http.bin
          tar cvzf ezdv-$GITHUB_REF_NAME-ota.tar.gz *.bin
          mv http.bin http_0.bin
          cp ../bootloader/bootloader.bin .
          cp ../ota_data_initial.bin .
          cp ../partition_table/partition-table.bin .
          tar cvzf ezdv-$GITHUB_REF_NAME-full.tar.gz *.bin

      - name: Upload release assets
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: true
          files: |
            ./firmware/build/release/ezdv-${{ github.ref_name }}-ota.tar.gz
            ./firmware/build/release/ezdv-${{ github.ref_name }}-full.tar.gz
